import { Inter } from "next/font/google";
import "./globals.css";
import { DataProvider } from "./pages/context/DataContext";
import 'primereact/resources/themes/lara-light-indigo/theme.css';  // Importa el tema predefinido
import 'primereact/resources/primereact.min.css';  // Importa los estilos principales de PrimeReact
import 'primeicons/primeicons.css';  // Importa los íconos de PrimeIcons


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Vinculaciòn Clientes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <DataProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </DataProvider>

  );
}
